### ISSUE TITLE
代码运行出错

### ISSUE THREAD

**Issue by HappyBoyss** [CCIIPLab/BiSyn_GAT_plus#3]
Traceback (most recent call last):
  File "F:/BiSyn_GAT_plus-main/BiSyn_GAT_plus-main/train.py", line 186, in <module>
    run(args, vocab, tokenizer = bert_tokenizer)
  File "F:/BiSyn_GAT_plus-main/BiSyn_GAT_plus-main/train.py", line 149, in run
    train_dataloader, valid_dataloader, test_dataloader = load_data(args, vocab, tokenizer=tokenizer)
  File "F:\BiSyn_GAT_plus-main\BiSyn_GAT_plus-main\snippet.py", line 150, in load_data
    vocab = vocab, tokenizer = tokenizer, is_shuffle = True)
  File "F:\BiSyn_GAT_plus-main\BiSyn_GAT_plus-main\snippet.py", line 130, in load_one_data
    one_dataset = ABSA_Dataset(args, file_name, vocab, tokenizer)
  File "F:\BiSyn_GAT_plus-main\BiSyn_GAT_plus-main\dataloader.py", line 31, in __init__
    self.data = self.process(raw_data, vocab, args, tokenizer)
  File "F:\BiSyn_GAT_plus-main\BiSyn_GAT_plus-main\dataloader.py", line 98, in process
    adj_i_oneshot = adj_i_oneshot * cd_adj 
UnboundLocalError: local variable 'cd_adj' referenced before assignment

**Comment by ShuoLiang-98** [comment]
新更新的dataloader.py已修正该错误
